### ISSUE TITLE
No idea...

### ISSUE THREAD

**Issue by ricardoroehe** [tassaron2/symlink-editor#1]
Hey, tassaron! Thanks for the development! I can't believe a GUI for changing symlinks is not available anywhere... This should be ordinary!

Well, about my issue, I just can't change any symlink. The same warning appears everytime.

![Screenshot from 2019-11-27 11-49-06](https://user-images.githubusercontent.com/9118434/69733388-03d82c80-110c-11ea-9b57-19b7fc695ba1.png)
![Screenshot from 2019-11-27 11-49-23](https://user-images.githubusercontent.com/9118434/69733389-03d82c80-110c-11ea-98df-842c89a973f6.png)

Do you have any clue?

**Comment by tassaron** [comment]
This was my first GUI app and the code is really a mess... I'd like to totally rewrite it someday. But for now, let me know if 55c063b fixes your issue. It works for me now!

**Comment by ricardoroehe** [comment]
> This was my first GUI app and the code is really a mess... I'd like to totally rewrite it someday. But for now, let me know if [55c063b](https://github.com/tassaron2/symlink-editor/commit/55c063b7174c49504ed9ee2571f61ec44c50c012) fixes your issue. It works for me now!

It works! Thank you a lot!
